insert into `search_er_subcate` values ("강원도",10);
insert into `search_er_subcate` values ("경기도",11);
insert into `search_er_subcate` values ("경상남도",12);
insert into `search_er_subcate` values ("경상북도",13);
insert into `search_er_subcate` values ("광주광역시",14);
insert into `search_er_subcate` values ("대구광역시",15);
insert into `search_er_subcate` values ("대전광역시",16);
insert into `search_er_subcate` values ("부산광역시",17);
insert into `search_er_subcate` values ("서울특별시",18);
insert into `search_er_subcate` values ("세종특별자치시",19);
insert into `search_er_subcate` values ("울산광역시",20);
insert into `search_er_subcate` values ("인천광역시",21);
insert into `search_er_subcate` values ("전라남도",22);
insert into `search_er_subcate` values ("전라북도",23);
insert into `search_er_subcate` values ("제주특별자치도",24);
insert into `search_er_subcate` values ("충청남도",25);
insert into `search_er_subcate` values ("충청북도",26);



insert into `search_er_subcate` values ("삼척시",10,1);
insert into `search_er_subcate` values ("화천군",10,2);
insert into `search_er_subcate` values ("고성군",10,3);
insert into `search_er_subcate` values ("철원군",10,4);
insert into `search_er_subcate` values ("횡성군",10,5);
insert into `search_er_subcate` values ("춘천시",10,6);
insert into `search_er_subcate` values ("강릉시",10,7);
insert into `search_er_subcate` values ("양양군",10,8);
insert into `search_er_subcate` values ("원주시",10,9);
insert into `search_er_subcate` values ("정선군",10,10);
insert into `search_er_subcate` values ("속초시",10,11);
insert into `search_er_subcate` values ("태백시",10,12);
insert into `search_er_subcate` values ("인제군",10,13);
insert into `search_er_subcate` values ("영월군",10,14);
insert into `search_er_subcate` values ("양구군",10,15);
insert into `search_er_subcate` values ("홍천군",10,16);
insert into `search_er_subcate` values ("평창군",10,17);
insert into `search_er_subcate` values ("동해시",10,18);
insert into `search_er_subcate` values ("여주시",11,1);
insert into `search_er_subcate` values ("의정부시",11,2);
insert into `search_er_subcate` values ("포천시",11,3);
insert into `search_er_subcate` values ("가평군",11,4);
insert into `search_er_subcate` values ("구리시",11,5);
insert into `search_er_subcate` values ("동안구",11,6);
insert into `search_er_subcate` values ("과천시",11,7);
insert into `search_er_subcate` values ("하남시",11,8);
insert into `search_er_subcate` values ("양평군",11,9);
insert into `search_er_subcate` values ("광주시",11,10);
insert into `search_er_subcate` values ("평택시",11,11);
insert into `search_er_subcate` values ("팔달구",11,12);
insert into `search_er_subcate` values ("수정구",11,13);
insert into `search_er_subcate` values ("일산동구",11,14);
insert into `search_er_subcate` values ("안성시",11,15);
insert into `search_er_subcate` values ("덕양구",11,16);
insert into `search_er_subcate` values ("단원구",11,17);
insert into `search_er_subcate` values ("의왕시",11,18);
insert into `search_er_subcate` values ("김포시",11,19);
insert into `search_er_subcate` values ("권선구",11,20);
insert into `search_er_subcate` values ("시흥시",11,21);
insert into `search_er_subcate` values ("이천시",11,22);
insert into `search_er_subcate` values ("영통구",11,23);
insert into `search_er_subcate` values ("광명시",11,24);
insert into `search_er_subcate` values ("양주시",11,25);
insert into `search_er_subcate` values ("군포시",11,26);
insert into `search_er_subcate` values ("파주시",11,27);
insert into `search_er_subcate` values ("기흥구",11,28);
insert into `search_er_subcate` values ("분당구",11,29);
insert into `search_er_subcate` values ("연천군",11,30);
insert into `search_er_subcate` values ("남양주시",11,31);
insert into `search_er_subcate` values ("중원구",11,32);
insert into `search_er_subcate` values ("화성시",11,33);
insert into `search_er_subcate` values ("용인시 처인구",11,34);
insert into `search_er_subcate` values ("처인구",11,35);
insert into `search_er_subcate` values ("오산시",11,36);
insert into `search_er_subcate` values ("부천시",11,37);
insert into `search_er_subcate` values ("일산서구",11,38);
insert into `search_er_subcate` values ("수지구",11,39);
insert into `search_er_subcate` values ("만안구",11,40);
insert into `search_er_subcate` values ("상록구",11,41);
insert into `search_er_subcate` values ("동두천시",11,42);
insert into `search_er_subcate` values ("장안구",11,43);
insert into `search_er_subcate` values ("여주시",11,44);
insert into `search_er_subcate` values ("밀양시",12,1);
insert into `search_er_subcate` values ("의령군",12,2);
insert into `search_er_subcate` values ("거창군",12,3);
insert into `search_er_subcate` values ("합천군",12,4);
insert into `search_er_subcate` values ("함안군",12,5);
insert into `search_er_subcate` values ("성산구",12,6);
insert into `search_er_subcate` values ("마산합포구",12,7);
insert into `search_er_subcate` values ("진주시",12,8);
insert into `search_er_subcate` values ("양산시",12,9);
insert into `search_er_subcate` values ("고성군",12,10);
insert into `search_er_subcate` values ("거제시",12,11);
insert into `search_er_subcate` values ("진해구",12,12);
insert into `search_er_subcate` values ("창녕군",12,13);
insert into `search_er_subcate` values ("하동군",12,14);
insert into `search_er_subcate` values ("남해군",12,15);
insert into `search_er_subcate` values ("사천시",12,16);
insert into `search_er_subcate` values ("통영시",12,17);
insert into `search_er_subcate` values ("창원시 마산합포구",12,18);
insert into `search_er_subcate` values ("마산회원구",12,19);
insert into `search_er_subcate` values ("산청군",12,20);
insert into `search_er_subcate` values ("창원시 마산회원구",12,21);
insert into `search_er_subcate` values ("김해시",12,22);
insert into `search_er_subcate` values ("창원시 의창구",12,23);
insert into `search_er_subcate` values ("의창구",12,24);
insert into `search_er_subcate` values ("함양군",12,25);
insert into `search_er_subcate` values ("칠곡군",13,1);
insert into `search_er_subcate` values ("문경시",13,2);
insert into `search_er_subcate` values ("의성군",13,3);
insert into `search_er_subcate` values ("성주군",13,4);
insert into `search_er_subcate` values ("영주시",13,5);
insert into `search_er_subcate` values ("청도군",13,6);
insert into `search_er_subcate` values ("김천시",13,7);
insert into `search_er_subcate` values ("예천군",13,8);
insert into `search_er_subcate` values ("경주시",13,9);
insert into `search_er_subcate` values ("영덕군",13,10);
insert into `search_er_subcate` values ("안동시",13,11);
insert into `search_er_subcate` values ("고령군",13,12);
insert into `search_er_subcate` values ("상주시",13,13);
insert into `search_er_subcate` values ("영천시",13,14);
insert into `search_er_subcate` values ("군위군",13,15);
insert into `search_er_subcate` values ("구미시",13,16);
insert into `search_er_subcate` values ("포항시 남구",13,17);
insert into `search_er_subcate` values ("남구",13,18);
insert into `search_er_subcate` values ("울진군",13,19);
insert into `search_er_subcate` values ("포항시 북구",13,20);
insert into `search_er_subcate` values ("북구",13,21);
insert into `search_er_subcate` values ("경산시",13,22);
insert into `search_er_subcate` values ("봉화군",13,23);
insert into `search_er_subcate` values ("청송군",13,24);
insert into `search_er_subcate` values ("울릉군",13,25);
insert into `search_er_subcate` values ("영양군",13,26);
insert into `search_er_subcate` values ("동구",14,1);
insert into `search_er_subcate` values ("광산구",14,2);
insert into `search_er_subcate` values ("서구",14,3);
insert into `search_er_subcate` values ("달성군",15,1);
insert into `search_er_subcate` values ("수성구",15,2);
insert into `search_er_subcate` values ("달서구",15,3);
insert into `search_er_subcate` values ("중구",15,4);
insert into `search_er_subcate` values ("유성구",16,1);
insert into `search_er_subcate` values ("대덕구",16,2);
insert into `search_er_subcate` values ("부산진구",17,1);
insert into `search_er_subcate` values ("사상구",17,2);
insert into `search_er_subcate` values ("사하구",17,3);
insert into `search_er_subcate` values ("강서구",17,4);
insert into `search_er_subcate` values ("연제구",17,5);
insert into `search_er_subcate` values ("수영구",17,6);
insert into `search_er_subcate` values ("금정구",17,7);
insert into `search_er_subcate` values ("기장군",17,8);
insert into `search_er_subcate` values ("동래구",17,9);
insert into `search_er_subcate` values ("영도구",17,10);
insert into `search_er_subcate` values ("해운대구",17,11);
insert into `search_er_subcate` values ("송파구",18,1);
insert into `search_er_subcate` values ("구로구",18,2);
insert into `search_er_subcate` values ("금천구",18,3);
insert into `search_er_subcate` values ("종로구",18,4);
insert into `search_er_subcate` values ("은평구",18,5);
insert into `search_er_subcate` values ("강동구",18,6);
insert into `search_er_subcate` values ("강남구",18,7);
insert into `search_er_subcate` values ("마포구",18,8);
insert into `search_er_subcate` values ("노원구",18,9);
insert into `search_er_subcate` values ("광진구",18,10);
insert into `search_er_subcate` values ("성동구",18,11);
insert into `search_er_subcate` values ("성북구",18,12);
insert into `search_er_subcate` values ("관악구",18,13);
insert into `search_er_subcate` values ("서대문구",18,14);
insert into `search_er_subcate` values ("용산구",18,15);
insert into `search_er_subcate` values ("서초구",18,16);
insert into `search_er_subcate` values ("동작구",18,17);
insert into `search_er_subcate` values ("동대문구",18,18);
insert into `search_er_subcate` values ("영등포구",18,19);
insert into `search_er_subcate` values ("도봉구",18,20);
insert into `search_er_subcate` values ("중랑구",18,21);
insert into `search_er_subcate` values ("양천구",18,22);
insert into `search_er_subcate` values ("강북구",18,23);
insert into `search_er_subcate` values ("세종특별자치시",19,1);
insert into `search_er_subcate` values ("울주군",20,1);
insert into `search_er_subcate` values ("남동구",21,1);
insert into `search_er_subcate` values ("부평구",21,2);
insert into `search_er_subcate` values ("계양구",21,3);
insert into `search_er_subcate` values ("강화군",21,4);
insert into `search_er_subcate` values ("미추홀구",21,5);
insert into `search_er_subcate` values ("옹진군",21,6);
insert into `search_er_subcate` values ("연수구",21,7);
insert into `search_er_subcate` values ("순천시",22,1);
insert into `search_er_subcate` values ("담양군",22,2);
insert into `search_er_subcate` values ("구례군",22,3);
insert into `search_er_subcate` values ("강진군",22,4);
insert into `search_er_subcate` values ("곡성군",22,5);
insert into `search_er_subcate` values ("보성군",22,6);
insert into `search_er_subcate` values ("목포시",22,7);
insert into `search_er_subcate` values ("나주시",22,8);
insert into `search_er_subcate` values ("여수시",22,9);
insert into `search_er_subcate` values ("해남군",22,10);
insert into `search_er_subcate` values ("진도군",22,11);
insert into `search_er_subcate` values ("완도군",22,12);
insert into `search_er_subcate` values ("고흥군",22,13);
insert into `search_er_subcate` values ("장흥군",22,14);
insert into `search_er_subcate` values ("광양시",22,15);
insert into `search_er_subcate` values ("영광군",22,16);
insert into `search_er_subcate` values ("영암군",22,17);
insert into `search_er_subcate` values ("함평군",22,18);
insert into `search_er_subcate` values ("장성군",22,19);
insert into `search_er_subcate` values ("화순군",22,20);
insert into `search_er_subcate` values ("신안군",22,21);
insert into `search_er_subcate` values ("무안군",22,22);
insert into `search_er_subcate` values ("김제시",23,1);
insert into `search_er_subcate` values ("익산시",23,2);
insert into `search_er_subcate` values ("남원시",23,3);
insert into `search_er_subcate` values ("정읍시",23,4);
insert into `search_er_subcate` values ("임실군",23,5);
insert into `search_er_subcate` values ("전주시 덕진구",23,6);
insert into `search_er_subcate` values ("군산시",23,7);
insert into `search_er_subcate` values ("전주시 완산구",23,8);
insert into `search_er_subcate` values ("완주군",23,9);
insert into `search_er_subcate` values ("장수군",23,10);
insert into `search_er_subcate` values ("부안군",23,11);
insert into `search_er_subcate` values ("고창군",23,12);
insert into `search_er_subcate` values ("순창군",23,13);
insert into `search_er_subcate` values ("진안군",23,14);
insert into `search_er_subcate` values ("무주군",23,15);
insert into `search_er_subcate` values ("서귀포시",24,1);
insert into `search_er_subcate` values ("제주시",24,2);
insert into `search_er_subcate` values ("논산시",25,1);
insert into `search_er_subcate` values ("서산시",25,2);
insert into `search_er_subcate` values ("홍성군",25,3);
insert into `search_er_subcate` values ("공주시",25,4);
insert into `search_er_subcate` values ("태안군",25,5);
insert into `search_er_subcate` values ("당진시",25,6);
insert into `search_er_subcate` values ("예산군",25,7);
insert into `search_er_subcate` values ("천안시 동남구",25,8);
insert into `search_er_subcate` values ("부여군",25,9);
insert into `search_er_subcate` values ("금산군",25,10);
insert into `search_er_subcate` values ("보령시",25,11);
insert into `search_er_subcate` values ("아산시",25,12);
insert into `search_er_subcate` values ("계룡시",25,13);
insert into `search_er_subcate` values ("서천군",25,14);
insert into `search_er_subcate` values ("청양군",25,15);
insert into `search_er_subcate` values ("천안시 서북구",25,16);
insert into `search_er_subcate` values ("청주시 흥덕구",26,1);
insert into `search_er_subcate` values ("단양군",26,2);
insert into `search_er_subcate` values ("청주시 상당구",26,3);
insert into `search_er_subcate` values ("충주시",26,4);
insert into `search_er_subcate` values ("음성군",26,5);
insert into `search_er_subcate` values ("괴산군",26,6);
insert into `search_er_subcate` values ("제천시",26,7);
insert into `search_er_subcate` values ("청주시 서원구",26,8);
insert into `search_er_subcate` values ("진천군",26,9);




insert into `search_er_subcate` values ("옥천군",26,10);
insert into `search_er_subcate` values ("청주시 청원구",26,11);
insert into `search_er_subcate` values ("보은군",26,12);
insert into `search_er_subcate` values ("증평군",26,13);
insert into `search_er_subcate` values ("영동군",26,14);

select * from `search_er_subcate` where `region_code` = 10;

SELECT a.`region`, b.* FROM `search_er_cate` AS a
JOIN `search_er_subcate` AS b WHERE a.region_code = b.region_code;


UPDATE `swiftER`.`search_er_subcate` SET `region`='경기도' WHERE  `region_code`=11;
UPDATE `swiftER`.`search_er_subcate` SET `region`='경상남도' WHERE  `region_code`=12;
UPDATE `swiftER`.`search_er_subcate` SET `region`='경상북도' WHERE  `region_code`=13;
UPDATE `swiftER`.`search_er_subcate` SET `region`='광주광역시' WHERE  `region_code`=14;
UPDATE `swiftER`.`search_er_subcate` SET `region`='대구광역시' WHERE  `region_code`=15;
UPDATE `swiftER`.`search_er_subcate` SET `region`='대전광역시' WHERE  `region_code`=16;
UPDATE `swiftER`.`search_er_subcate` SET `region`='부산광역시' WHERE  `region_code`=17;
UPDATE `swiftER`.`search_er_subcate` SET `region`='서울특별시' WHERE  `region_code`=18;
UPDATE `swiftER`.`search_er_subcate` SET `region`='세종특별자치시' WHERE  `region_code`=19;
UPDATE `swiftER`.`search_er_subcate` SET `region`='울산광역시' WHERE  `region_code`=20;
UPDATE `swiftER`.`search_er_subcate` SET `region`='인천광역시' WHERE  `region_code`=21;
UPDATE `swiftER`.`search_er_subcate` SET `region`='전라남도' WHERE  `region_code`=22;
UPDATE `swiftER`.`search_er_subcate` SET `region`='전라북도' WHERE  `region_code`=23;
UPDATE `swiftER`.`search_er_subcate` SET `region`='제주특별자치도' WHERE  `region_code`=24;
UPDATE `swiftER`.`search_er_subcate` SET `region`='충청남도' WHERE  `region_code`=25;
UPDATE `swiftER`.`search_er_subcate` SET `region`='충청북도' WHERE  `region_code`=26;



select * from `search_er_review` where `hospital_code` = '123123';